This is the description

   12.0       : Tmin_default Default minimum temperature (°Ã) if no temperature file is specified
   28.0       : Tmax_default Default maximum temperature (°Ã) if no temperature file is specified
   20         : Germination Required soil water content in top soil for germination (% TAW)

//Other items to be added in the program settings
     -6             : Shape factor for effect water stress on root zone expansion
      3             : Number of days after which deficient aeration is fully effective
      1.00        : Exponent of senescence factor adjusting drop in photosynthetic activity of dying crop
      0.30        : Considered depth (m) of soil profile for calculation of mean soil water content for CN adjustment
      1             : CN is adjusted to Antecedent Moisture Class
     20            : salt diffusion factor (capacity for salt diffusion in micro pores) [%]
    100           : salt solubility [g/liter]
     16            : shape factor for effect of soil water content gradient on capillary rise
