// CropModelMKS_Plant_None.idl: CropModelMKS_Plant_None 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(CropModelMKSPlantNone.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(667732c2-14dd-4a0a-b81d-4b83ac172434),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IComponent : IDispatch
{
	[id(1)] HRESULT Update([in] IDispatch* states);
	[id(2)] HRESULT Initialize([in] IDispatch* states, [in] IDispatch* parameters);
	[id(3)] HRESULT Inquire([in] BSTR name, [in] IDispatch* states);
	[id(4)] HRESULT Description([in] BSTR path);
	[id(5)] HRESULT Convert([in] BSTR file_path, [in] BSTR xml_path);
};
[
	uuid(c6705f1f-3c9d-45e5-990d-6222fcd45cbf),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{06f4fbb2-5324-480c-8206-a2a6df3ed846}")
]
library CropModelMKSPlantNoneLib
{
	importlib("stdole2.tlb");
	[
		uuid(06f4fbb2-5324-480c-8206-a2a6df3ed846)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(2dae3cbd-93df-4dc9-b664-05e312f5c88a)
	]
	coclass Component
	{
		[default] interface IComponent;
	};
};

import "shobjidl.idl";
