// Management_Schedule_Example.idl: Management_Schedule_Example 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(ManagementScheduleExample.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(1fe63ef0-a1d3-4724-ac95-299f35f2a247),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IComponent : IDispatch
{
	[id(1)] HRESULT Update([in] IDispatch* states);
	[id(2)] HRESULT Initialize([in] IDispatch* states, [in] IDispatch* parameters);
	[id(3)] HRESULT Inquire([in] BSTR name, [in] IDispatch* states);
	[id(4)] HRESULT Description([in] BSTR path);
	[id(5)] HRESULT Convert([in] BSTR file_path, [in] BSTR xml_path);
};
[
	uuid(44a06f19-414b-42b1-a9af-5520123f745a),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{63f525d8-8173-4f81-a67e-e2ebb6003a9a}")
]
library ManagementScheduleExampleLib
{
	importlib("stdole2.tlb");
	[
		uuid(63f525d8-8173-4f81-a67e-e2ebb6003a9a)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(077ee56d-94ea-479b-98ee-5385a99a5685)
	]
	coclass Component
	{
		[default] interface IComponent;
	};
};

import "shobjidl.idl";
